# Generated by Django 4.2 on 2023-05-01 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Song', '0003_alter_song_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('list_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='list_id')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('cover', models.ImageField(default='', upload_to='', verbose_name='cover')),
                ('tag1', models.CharField(default='', max_length=30, verbose_name='tag1')),
                ('tag2', models.CharField(default='', max_length=30, verbose_name='tag2')),
                ('tag3', models.CharField(default='', max_length=30, verbose_name='tag3')),
                ('tag4', models.CharField(default='', max_length=30, verbose_name='tag4')),
                ('tag5', models.CharField(default='', max_length=30, verbose_name='tag5')),
                ('tag6', models.CharField(default='', max_length=30, verbose_name='tag6')),
                ('content', models.ManyToManyField(to='Song.song')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
