# Generated by Django 4.2 on 2023-05-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongList', '0003_likelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlist',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='title'),
        ),
    ]
