# Generated by Django 4.2 on 2023-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongList', '0004_alter_songlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='likelist',
            name='sharable',
            field=models.BooleanField(default=False, verbose_name='sharable'),
        ),
        migrations.AddField(
            model_name='songlist',
            name='sharable',
            field=models.BooleanField(default=False, verbose_name='sharable'),
        ),
    ]
