# Generated by Django 4.2 on 2023-05-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongList', '0005_likelist_sharable_songlist_sharable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songlist',
            name='cover',
        ),
        migrations.AddField(
            model_name='songlist',
            name='has_cover',
            field=models.BooleanField(default=False, verbose_name='has_cover'),
        ),
    ]
