# Generated by Django 4.2 on 2023-05-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SongList', '0006_remove_songlist_cover_songlist_has_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likelist',
            name='cover',
        ),
        migrations.AlterField(
            model_name='likelist',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
