# Generated by Django 4.2 on 2023-05-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SongList', '0007_remove_likelist_cover_alter_likelist_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likelist',
            name='sharable',
        ),
        migrations.RemoveField(
            model_name='likelist',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='likelist',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='likelist',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='likelist',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='likelist',
            name='tag5',
        ),
        migrations.RemoveField(
            model_name='likelist',
            name='tag6',
        ),
    ]
