# Generated by Django 4.2 on 2023-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongList', '0008_remove_likelist_sharable_remove_likelist_tag1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlist',
            name='introduction',
            field=models.CharField(default='暂无介绍', max_length=200),
        ),
    ]
