# Generated by Django 4.2 on 2023-05-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
        migrations.AddField(
            model_name='user',
            name='has_icon',
            field=models.BooleanField(default=False, verbose_name='has_icon'),
        ),
    ]
