# Generated by Django 4.2 on 2023-05-01 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tag1',
            field=models.CharField(default='', max_length=30, verbose_name='tag1'),
        ),
        migrations.AddField(
            model_name='song',
            name='tag2',
            field=models.CharField(default='', max_length=30, verbose_name='tag2'),
        ),
        migrations.AddField(
            model_name='song',
            name='tag3',
            field=models.CharField(default='', max_length=30, verbose_name='tag3'),
        ),
        migrations.AddField(
            model_name='song',
            name='tag4',
            field=models.CharField(default='', max_length=30, verbose_name='tag4'),
        ),
        migrations.AddField(
            model_name='song',
            name='tag5',
            field=models.CharField(default='', max_length=30, verbose_name='tag5'),
        ),
        migrations.AddField(
            model_name='song',
            name='tag6',
            field=models.CharField(default='', max_length=30, verbose_name='tag6'),
        ),
        migrations.AddField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyric',
            field=models.URLField(default='', verbose_name='Lyric'),
        ),
    ]
