# Generated by Django 4.2 on 2023-05-02 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0003_alter_song_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, '喜欢数不能小于0')], verbose_name='like'),
        ),
    ]
