# Generated by Django 4.2 on 2023-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0004_song_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audit_ok',
            field=models.BooleanField(default=False, verbose_name='audit_ok'),
        ),
    ]
