# Generated by Django 4.2 on 2023-05-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0005_song_audit_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyric',
        ),
    ]
