# Generated by Django 4.2 on 2023-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0006_remove_song_cover_remove_song_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='has_cover',
            field=models.BooleanField(default=False, verbose_name='has_cover'),
        ),
        migrations.AddField(
            model_name='song',
            name='has_lyric',
            field=models.BooleanField(default=False, verbose_name='has_lyric'),
        ),
    ]
