# Generated by Django 4.2 on 2023-05-18 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0007_song_has_cover_song_has_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='played',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, '播放量不能小于0')], verbose_name='like'),
        ),
    ]
