# Generated by Django 4.2 on 2023-06-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0012_alter_song_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(default='Various Artists', max_length=30, verbose_name='Singer'),
        ),
    ]
